### ISSUE TITLE
Can you provide your .fonts files? Or tell how to download your fonts?

### ISSUE THREAD

**Issue by n0yal** [sarveshspatil111/i3wm-nord#1]

**Comment by TheDistroHopper** [comment]
Font name: Source Code Pro
#### Installation 
On Arch : <code>sudo pacman -S adobe-source-code-pro-fonts</code>
On Ubuntu : [Follow this link](https://www.rogerpence.com/posts/install-source-code-pro-font-on-ubuntu)
