### ISSUE TITLE
i3status icons

### ISSUE THREAD

**Issue by FeAx7** [sarveshspatil111/i3wm-nord#2]
Hi,
Fantastic theme.
Can you provide your i3status icons ? Where to download them ?
Also how did you customize thunar ?
Thks,

**Comment by TheDistroHopper** [comment]
Hey @FeAx7, thanks for the compliment.
I have used [font awesome](https://fontawesome.com/v5/cheatsheet) in my i3status, if you want to download it on your system then follow these commands :

- On Arch
```bash
yay -S ttf-font-awesome-4
```

- On Ubuntu
```bash
sudo apt install fonts-font-awesome
```

**Comment by TheDistroHopper** [comment]
Also @FeAx7 , I haven't did anything extra for thunar
I have only toggled the sidebar
You can also do this by pressing `` Ctrl + b``
